### ISSUE TITLE
Python function that extract signatures of JS functions from JS code

### ISSUE THREAD

**Issue by thorwhalen** [cosmograph-org/py_cosmograph#8]
Want a function that will extract signatures of JS functions from JS code.

```python
extract_js_functions(js_code_or_file)
# Returns a dict: `{function_name: function_signature, ...}`
```

In the "Only using bridging with functions" section of the [Where should JS code and templates be stored](https://github.com/cosmograph-org/py_cosmograph/issues/5) issue, I proposed a possible clean and reusable setup to call JS from python which requires the extraction of JS function signatures from JS code. See more context and details in the [issue](https://github.com/cosmograph-org/py_cosmograph/issues/5) itself. 

For parsing JS, I found this:
* [esprima](https://pypi.org/project/esprima/)
* [pyjsparser](https://pypi.org/project/pyjsparser/)

Apparently they're both lightweight (no third party deps), but they're not **super** popular or maintained. 

If they're functional, I might start with that, isolating just what I need through a facade, and replacing their use with my own regular expression based parser (we only need a very specific extraction here) in case we need to.

**Comment by thorwhalen** [comment]
[pyjsparser](https://pypi.org/project/pyjsparser/) didn't work out of the box for either "js-py-bridge.js" or "cosmos-iife-bundle.js".

On the other hand, [esprima](https://pypi.org/project/esprima/) did out of the box. 

It gives me an AST object of the parsed code. 

Pro: As long as the JS is parsable (by esprima -- because pyjsparser couldn't!), we get a much more robust solution.

Con: We'll need to understand the AST object enough to know how to extract the information we need. Perhaps using [glom](https://pypi.org/project/glom/). 

I'll give it a time-boxed try, but it may be easier to just do a not-too-robust regular expression for now...

**Comment by rokotyan** [comment]
@thorwhalen Looks like a great feature! But also seems to be an overkill at this point.

I think a simple accessor string logic will be enough for now. For example, in Python you write 
```
'style.color'
```

And the JS adaptor will translate it into a function:

```js
d => d.style.color
```

**Comment by thorwhalen** [comment]
@rokotyan: I'm not sure what you mean by the to  perhaps, but if you mean we have a function that translates dot-separated strings (e.g. `'style.color'`) into (strings that define) JS accessor functions (e.g. `d => d.style.color`) then, though indeed this could be useful, it doesn't seem even close to sufficient; and if so, we'll end up having to write many such mini-languages to bridge JS and Python. 

But perhaps I'm misunderstanding your example. 

Let's discuss more, offline, what you and I mean and think we need.
